title: Michele Costabile
description: A developer's blog
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal
twitter_username: cosmic53
github_username:  michelecos

options:
  - jekyll-mentions
